kind: Deployment
replicaCount: 1
name: sms-batch-delete-transaction-sms-dr
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-delete-transaction-sms-dr
  tag: prod-f7e5f346b58fad3c3a365ab77dda558066ef10b6
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  BatchSize: "50000"
  MongoConnectSend: "mongodb://root:J7yWBFyBsJ@mongosend-mongodb.database.svc.cluster.local:27017"
  MongoDataBaseNameSend: "send"
  MongoCollectionNameSend: "transaction"
  MongoConnectDR_True: "mongodb://root:ElqwJETIJN@mongodr-mongodb.database.svc.cluster.local:27017"
  MongoDataBaseNameDR_True: "dr"
  MongoCollectionNameDR_True: "deliveryreport_true"
  MongoConnectDR_Dtac: "mongodb://root:ElqwJETIJN@mongodr-mongodb.database.svc.cluster.local:27017"
  MongoDataBaseNameDR_Dtac: "dr"
  MongoCollectionNameDR_Dtac: "deliveryreport_dtac"
  timers: "60000"
  Interval: "60000"
  batchname: "batch DR Center Create Transaction"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: sms-batch-delete-transaction-sms-dr-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-batch-delete-transaction-sms-dr
        type: DirectoryOrCreate
  volumeMounts:
    - name: sms-batch-delete-transaction-sms-dr-logs
      mountPath: /app/logs/sms-batch-delete-transaction-sms-dr-container