kind: Deployment
replicaCount: 1
name: sms-batch-report-recurring
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-report-recurring
  tag: prod-8b80fb9214f0585e633108a530667dd36f10e0c1
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  report_centerDb: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=REPORT_CENTER;Data Source=103.212.181.40,14430"
  Day_of_monthly: "5"
  DatabaseConnections: "hospital ants2 ants4 axa bmw ants1 promotech"
  # DatabaseConnections: "ants1 ants2 ants4 axa bmw promotech hospital"
  ants1: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  ants2: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS_ENV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  ants4: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS_ENV4;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  axa: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_AXA;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  bmw: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_BMW;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  promotech: "Data Source=115.31.154.120,14430;Initial Catalog=ENV_PROMOTECH;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  hospital: "Data Source=119.63.71.113,14430;Initial Catalog=ANTSSMS_Hospital;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  Interval: "10000"
  closeLog: "0"
  scheduleTime: "04:00"
  # ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: sms-batch-report-recurring-logs
      hostPath:
        path: /mnt/data/logs/devcenter-batch-report-recurring
        type: DirectoryOrCreate
  volumeMounts:
    - name: sms-batch-report-recurring-logs
      mountPath: /app/logs/sms-batch-report-recurring-container

