kind: Deployment
replicaCount: 1
name: sms-otp
image:
  repository: registry.ants.co.th/apps/sms/sms-otp
  tag: prod-5c68716d9e682ced60cc2e9db4d5a75bef3a82f9
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  # type: NodePort
  internalPort: 80
  externalPort: 80
  # nodePort: 30082 # สามารถเปลี่ยนเลข port นี้ตามที่ต้องการ

appEnv: 
  JWT_KEY: "db3OIsj+BXE9NZDy0t8W3TcNekrF+2d/1sFnWG4HnV8TZY30iTOdtVWJG8abWvB1GlOgJuQZdcF2Luqm/hccMw=="
  REDIS_HOST: "redis-otp-master.database.svc.cluster.local:6379"
  #ENV
  #dev: "redis-otp-dev-master.database.svc.cluster.local:6379"
  #ants: "redis-otp-ants-master.database.svc.cluster.local:6379"
  #ants2: "redis-otp-ants2-master.database.svc.cluster.local:6379"
  #ants4: "redis-otp-ants4-master.database.svc.cluster.local:6379"
  #axa: "redis-otp-axa-master.database.svc.cluster.local:6379"
  #bmw: "redis-otp-bmw-master.database.svc.cluster.local:6379"
  #hospital: "redis-otp-hospital-master.database.svc.cluster.local:6379"
  #promotech: "redis-otp-promotech-master.database.svc.cluster.local:6379"
  #ENV

  MONGO_CONNECTIONSTRING: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  MONGO_DB: "logdb"
  ALLOWEDHOSTS: "*"


  ANTS1_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSOTPV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  ANTS1_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  ANTS2_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSOTP_ENV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  ANTS2_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS_ENV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  ANTS4_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSOTP_ENV4;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  ANTS4_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSSMS_ENV4;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  AXA_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=OTP_AXA_V2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  AXA_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_AXA;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  BMW_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=OTP_BMW_V2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  BMW_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_BMW;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  HOSPITAL_DB_CON_OTP: "Data Source=119.63.71.113,14430;Initial Catalog=ANTSOTPV2_Hospital;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;Max Pool Size=200"
  HOSPITAL_DB_CON_SMS: "Data Source=119.63.71.113,14430;Initial Catalog=ANTSSMS_Hospital;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;Max Pool Size=200"

  PROMOTECH_DB_CON_OTP: "Data Source=115.31.154.120,14430;Initial Catalog=ANTSOTP_PROMOTECH;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  PROMOTECH_DB_CON_SMS: "Data Source=115.31.154.120,14430;Initial Catalog=ENV_PROMOTECH;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  DB_CON_ACCOUNT: "Data Source=103.212.181.33,14430;Initial Catalog=ANTSACCOUNT;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  ISOPERATOR: "TRUE"
  SMSTRANTYPE: "4"

  rabbitHost: "rabbitmqms.database.svc.cluster.local"
  rabbitUser: "user"
  rabbitPass: "qKDOW4AFalq1KtV8"

  rabbitQueueTrueIsGame: "2325131104"
  rabbitQueueTrue: "2317451111"
  rabbitQueueDtac: "service01"

  REDIS_TRANFER_CONNECT: "xxx"
  REDIS_TRANFER_KEY: "PUBAPI_LASTOTPREQ:"
  URLTRANSACTIONINFO: "http://13.76.244.175:9100/createTransactionInfo"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
nodeSelector:
      kubernetes.io/hostname : data-warehouse-2
volumes:
  enabled: true
  volume:
    - name: otp-logs
      hostPath:
        path: /mnt/data/logs/devcenter-app-otp
        type: DirectoryOrCreate
  volumeMounts:
    - name: otp-logs
      mountPath: /app/logs/otp-container