kind: Deployment
replicaCount: 1
name: sms-batch-update-callback
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-update-callback
  tag: prod-58a49e876c6388bbc56f359ac07234267cfd8d5f
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  general-sleep: 60
  task-env: 1
  listDb: "hospital ants2 ants4 axa bmw ants1 promotech"

  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS;Data Source=115.31.154.120,14430"
  tempdb-ants1: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  
  ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV2;Data Source=115.31.154.120,14430"
  tempdb-ants2: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP_ENV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV4;Data Source=115.31.154.120,14430"
  tempdb-ants4: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP_ENV4;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_AXA;Data Source=115.31.154.120,14430"
  tempdb-axa: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP_AXA;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_BMW;Data Source=115.31.154.120,14430"
  tempdb-bmw: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP_BMW;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ENV_PROMOTECH;Data Source=115.31.154.120,14430"
  tempdb-promotech: "Data Source=115.31.154.120,14430;Initial Catalog=SMS_REPORT_TEMP_PROMOTECH;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_Hospital;Data Source=119.63.71.113,14430"
  tempdb-hospital: "Data Source=119.63.71.113,14430;Initial Catalog=SMS_REPORT_TEMP_Hospital;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-update-callback-logs
      hostPath:
        path: /mnt/data/logs/devcenter-batch-update-callback
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-update-callback-logs
      mountPath: /app/logs/batch-update-callback-container

