kind: Deployment
replicaCount: 1
name: sms-gettoken
image:
  repository: registry.ants.co.th/apps/sms/sms-gettoken
  tag: prod-2d3c38ee7dabf7ef822132fa7a6afcfb221becf0
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  dbAccount: "Data Source=103.212.181.33,14430;Initial Catalog=ANTSACCOUNT;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True; Encrypt=False;"
  redisConnectionString: "redis-gettoken-master.database.svc.cluster.local:6379"
  redisKey: ""
  AllowedHosts: "*"
  Wheretype: "in"
  Account_where: "1150,4236,417,4268,4309,4432"
  Check_Account_Login: "0"
  encrypt-key: "db3OIsj+BXE9NZDy0t8W3TcNekrF+2d/1sFnWG4HnV8TZY30iTOdtVWJG8abWvB1GlOgJuQZdcF2Luqm/hccMw=="
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  closeLog: "0"
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}

volumes:
  enabled: true
  volume:
    - name: gettoken-logs
      hostPath:
        path: /mnt/data/logs/devcenter-gettoken
        type: DirectoryOrCreate
  volumeMounts:
    - name: gettoken-logs
      mountPath: /app/logs/sms-gettoken-container