kind: Deployment
replicaCount: 1
name: sms-batch-etl-commu-to-mongo
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-etl-commu-to-mongo
  tag: prod-4620672d6241d34135e5220a8e7922720eac93e3
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv:
  batchname: "batch-etl-commu-to-mongo"
  Interval: "10000"

  # list env and connection string start
  listDb: "hospital ants2 ants4 axa bmw ants1 promotech"

  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=115.31.154.120,14430"
  mongo-con-ants1: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-ants1: "logdb"

  ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_ENV2;Data Source=115.31.154.120,14430"
  mongo-con-ants2: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-ants2: "ants2"

  ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_ENV4;Data Source=115.31.154.120,14430"
  mongo-con-ants4: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-ants4: "ants4"
  
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_AXA;Data Source=115.31.154.120,14430"
  mongo-con-axa: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-axa: "axa"
  
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_BMW;Data Source=115.31.154.120,14430"
  mongo-con-bmw: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-bmw: "bmw"

  promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_PROMOTECH;Data Source=115.31.154.120,14430"
  mongo-con-promotech: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-promotech: "promotech"

  hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_Hospital;Data Source=119.63.71.113,14430"
  mongo-con-hospital: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010"
  mongo-db-hospital: "hospital"
  closeLog: "0"
  # list env and connection string end
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-etl-commu-to-mongo-logs
      hostPath:
        path: /mnt/data/logs/devcenter-batch-etl-commu-to-mongo
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-etl-commu-to-mongo-logs
      mountPath: /app/logs/batch-etl-commu-to-mongo-container

