kind: Deployment
replicaCount: 1
name: sms-public
image:
  repository: registry.ants.co.th/apps/sms/sms-public
  tag: prod-87b5aa04768914aceca014da80bd778b6a968d2a
  pullPolicy: IfNotPresent
  commandEnabled: false
imagePullSecrets:
  - ants-registry
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  AllowedHosts: "*"
  contentlength: "1600"
  ants1: "redis-public-ants-direct-master.database.svc.cluster.local:6379"
  ants2: "redis-public-ants2-direct-master.database.svc.cluster.local:6379"
  ants4: "redis-public-ants4-direct-master.database.svc.cluster.local:6379"
  axa: "redis-public-ants-direct-master.database.svc.cluster.local:6379"
  bmw: "redis-public-ants-direct-master.database.svc.cluster.local:6379"
  hospital: "redis-public-ants-direct-master.database.svc.cluster.local:6379"
  promotech: "redis-public-promotech-direct-master.database.svc.cluster.local:6379"
  RedisKey: "PUBAPI_SMSREQ:"
  envKey: ""
  enpointUrl: "https://private-dev-center.ants.co.th"
  enpointUrl_Otp: "https://otp-center.ants.co.th"
  enpointUrl_Token_API: "https://gettoken-dev-center.ants.co.th/api/GetToken/loginApi"
  enpointUrl_Token: "https://gettoken-dev-center.ants.co.th/api/GetToken/login"
  expireMinute: "120"
  SMSDB_1: "xxx"
  APISMS: "xxx"
  SMSDB_2: "xxx"
  ANTNotifyEntities: "xxx"
  ANTNotifyConnectionString: "xxx"
  AccountDb: "103.212.181.33,14430';Database='ANTSACCOUNT';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  ExceptionLogs: "Server=tcp:antsdb.database.windows.net,1433;Initial Catalog=LOGS_DB;Persist Security Info=False;User ID=ants_sa;Password='P@ssw0rd;';MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180;"
  SMS40: "Server='115.31.154.120,14430';Database='SMS_REPORT_TEMP';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  REPORT_CENTER: "Server='103.212.181.40,14430';Database='REPORT_CENTER';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  limitTotalMongo: "200000"
  ApiDeleteRedis: "https://sms-apideleteredis-prod.ants.co.th/api/redis/del"
  shortenUrlDomain: "xxxx"
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  closeLog: "0"
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}

volumes:
  enabled: true
  volume:
    - name: public-logs
      hostPath:
        path: /mnt/data/logs/devcenter-app-public
        type: DirectoryOrCreate
  volumeMounts:
    - name: public-logs
      mountPath: /app/logs/public-container