kind: Deployment
replicaCount: 1
name: sms-batch-import-person
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-import-person
  tag: prod-bc52e59b96b2e3f863b996e7c2ba350191028680
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  # list env and connection string start
  listDb: "hospital ants2 ants4 axa bmw ants1 promotech"
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS;Data Source=115.31.154.120,14430"
  ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV2;Data Source=115.31.154.120,14430"
  ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV4;Data Source=115.31.154.120,14430"
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_AXA;Data Source=115.31.154.120,14430"
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_BMW;Data Source=115.31.154.120,14430"
  promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ENV_PROMOTECH;Data Source=115.31.154.120,14430"
  hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_Hospital;Data Source=119.63.71.113,14430"
  task-env: "7"
  ecm-url : "http://119.63.68.220:51010/api/file/getfile/"
  ecm-username : "smsimport"
  ecm-password : "P@ssw0rd"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-import-person-logs
      hostPath:
        path: /mnt/data/logs/devcenter-batch-import-person
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-import-person-logs
      mountPath: /app/logs/batch-import-person-container