kind: Deployment
replicaCount: 1
name: sms-batch-callback
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-callback
  tag: prod-13d5e2266e7f6db6ddccc545a4d07cda9338f0d3
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  Interval: "3000"
  list-env: "hospital ants2 ants4 axa bmw ants1 promotech"
  # list-env: "ants1 ants2 ants4 axa bmw promotech hospital"
  
  #ants1 db config
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS;Data Source=115.31.154.120,14430"
  #mail config
  ants1_auth_email: "no-reply@message-info.me"
  ants1_auth_passowrd: "Ants2015$"
  ants1_emailto: "nuttapon.a@ants.co.th"

  #ants2 db config
  ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV2;Data Source=115.31.154.120,14430"
  #mail config
  ants2_auth_email: "no-reply@message-info.me"
  ants2_auth_passowrd: "Ants2015$"
  ants2_emailto: "nuttapon.a@ants.co.th"

  #ants4 db config
  ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_ENV4;Data Source=115.31.154.120,14430"
  #mail config
  ants4_auth_email: "no-reply@message-info.me"
  ants4_auth_passowrd: "Ants2015$"
  ants4_emailto: "nuttapon.a@ants.co.th"

  #axa db config
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_AXA;Data Source=115.31.154.120,14430"
  #mail config
  axa_auth_email: "no-reply@message-info.me"
  axa_auth_passowrd: "Ants2015$"
  axa_emailto: "nuttapon.a@ants.co.th"

    #bmw db config
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_BMW;Data Source=115.31.154.120,14430"
  #mail config
  bmw_auth_email: "no-reply@message-info.me"
  bmw_auth_passowrd: "Ants2015$"
  bmw_emailto: "nuttapon.a@ants.co.th"

  #promotech db config
  promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ENV_PROMOTECH;Data Source=115.31.154.120,14430"
  #mail config
  promotech_auth_email: "no-reply@message-info.me"
  promotech_auth_passowrd: "Ants2015$"
  promotech_emailto: "nuttapon.a@ants.co.th"

  #hospital db config
  hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSSMS_Hospital;Data Source=119.63.71.113,14430"
  #mail config
  hospital_auth_email: "no-reply@message-info.me"
  hospital_auth_passowrd: "Ants2015$"
  hospital_emailto: "nuttapon.a@ants.co.th"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-callback-logs
      hostPath:
        path: /mnt/data/logs/devcenter-batch-callback
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-callback-logs
      mountPath: /app/logs/batch-callback-container

