{{ if .Values.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.Secretname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}  
