kind: Deployment
replicaCount: 1
name: sms-batch-report-otp
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-report-otp
  tag: dev-df3fe8a1fe9a3706fb7ecc2b1be515cc2a523cdc
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  ANTSLNSConnectionString: "Data Source=210.1.61.185,14430;Initial Catalog=SMS_KUBE;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True; Encrypt=False;"
  ReportCenter: "Data Source=210.1.61.185,14430;Initial Catalog=REPORT_CENTER;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True; Encrypt=False;"
  ACCOUNT: "Data Source=210.1.61.185,14430;Initial Catalog=ACCOUNT_KUBE;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True; Encrypt=False;"
  MongoConnect: "mongodb://admin:P%40ssw0rd%3B@210.1.61.185:37010"
  MongoDataBaseName: "logdb"
  MongoCollectionName: "transactions_MonthlyCommu"
  MongoCollectionShortenName: "transactions_MonthlyCommu"
  RowAmount: "500000"
  Interval: "1000"
  batchname: "batch reportCommu UAT"
  nodeApiURL: "http://103.212.181.11:3001"
  timers: "100000"
  path: "C:\\Report\\"
  shortenUrlDomain: "c0c.ants.co.th/"
  offsets: "100000"
  sleep: "10000"
  maxRows: "100000"
  buffers: "500000"
  isThreads: "5"
  Day_of_monthly: "5"
  ECM.URL: "http://119.63.68.220:51010/api/file/getfile/"
  UploadNewEcm_Url: "http://192.168.10.12:51010/api/file/uploadfile_formdata"
  auth_newecm: "smsnewreport:P@ssw0rd"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: sms-batch-report-otp-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-batch-report-otp
        type: DirectoryOrCreate
  volumeMounts:
    - name: sms-batch-report-otp-logs
      mountPath: /app/logs/sms-batch-report-otp-container