kind: Deployment
replicaCount: 1
name: sms-analyst
image:
  repository: registry.ants.co.th/apps/sms/sms-api-analyst
  tag: dev-8658783d2d9e7ecd74e6de944749f2f721ad817e
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv:
  AllowedHosts: "*"
  contentlength: "1600"
  Account: "Data Source=210.1.61.185,14430;Initial Catalog=ACCOUNT_KUBE;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  Blacklist: "Data Source=210.1.61.185,14430;Initial Catalog=BLACKLIST;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"

  ants1: "Data Source=210.1.61.185,14430;Initial Catalog=SMS_KUBE;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  axa: "Data Source=210.1.61.185,14430;Initial Catalog=SMS_KUBE_PROD_ENV1;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  bmw: "Data Source=210.1.61.185,14430;Initial Catalog=SMS_KUBE_PROD_ENV2;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'; TrustServerCertificate=True;"
  encrypt-key: "db3OIsj+BXE9NZDy0t8W3TcNekrF+2d/1sFnWG4HnV8TZY30iTOdtVWJG8abWvB1GlOgJuQZdcF2Luqm/hccMw=="
  AccountID: "712"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: api-analyst-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-api-analyst
        type: DirectoryOrCreate
  volumeMounts:
    - name: api-analyst-logs
      mountPath: /app/logs/api-analyst-container

