kind: Deployment
replicaCount: 1
name: sms-batch-ftp-export
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-ftp-export
  tag: dev-8f5927bb6386712ee0c491f9e87741eed845b7ec
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  Interval: "3000"
  batchname: "FTP Export"

  EnvSelection: "dev"

  dev_auth_newecm: "smsapi:P@ssw0rd"
  dev_ECM_ENDPOINT: "http://119.63.68.220:51010"
  dev_smsDb: "Server='210.1.61.185,14430';Database='SMS_KUBE';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  dev_accountDb: "Server='210.1.61.185,14430';Database='ACCOUNT_KUBE';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True"
  closeLog: "0"

  #ants1_auth_newecm: xxxx
  #ants1_ECM_ENDPOINT: xxxx
  #ants1_smsDb: xxxx
  #ants1_accountDb: xxxx
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-ftp-export-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-batch-ftp-export
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-ftp-export-logs
      mountPath: /app/logs/batch-ftp-export-container

