kind: Deployment
replicaCount: 1
name: sms-batch-etl-commu-to-mongo
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-etl-commu-to-mongo
  tag: dev-4620672d6241d34135e5220a8e7922720eac93e3
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv:
  batchname: "xxxxx"
  Interval: "10000"
  closeLog: "0"
  # list env and connection string start
  listDb: "ants1 axa"
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_ENV1;Data Source=210.1.61.185,14430"
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  mongo-con-ants1: "mongodb://210.1.61.187:37017"
  mongo-db-ants1: "logdb"
  mongo-con-axa: "mongodb://210.1.61.187:37017"
  mongo-db-axa: "axa"
  mongo-con-bmw: "mongodb://210.1.61.187:37017"
  mongo-db-bmw: "bmw"
  # list env and connection string end
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-etl-commu-to-mongo-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-batch-etl-commu-to-mongo
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-etl-commu-to-mongo-logs
      mountPath: /app/logs/batch-etl-commu-to-mongo-container

