kind: Deployment
replicaCount: 1
name: sms-batch-import-person
image:
  repository: registry.ants.co.th/apps/sms/sms-batch-import-person
  tag: dev-bc52e59b96b2e3f863b996e7c2ba350191028680
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  # list env and connection string start
  listDb: "ants1 axa"
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE;Data Source=210.1.61.185,14430"
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV1;Data Source=210.1.61.185,14430"
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV2;Data Source=210.1.61.185,14430"
  task-env: "3"
  ecm-url : "http://192.168.10.12:51010/api/file/getfile/"
  ecm-username : "smsimport"
  ecm-password : "P@ssw0rd"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: batch-import-person-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-batch-import-person
        type: DirectoryOrCreate
  volumeMounts:
    - name: batch-import-person-logs
      mountPath: /app/logs/batch-import-person-container