kind: Deployment
replicaCount: 1
name: sms-publictoredis
image:
  repository: registry.ants.co.th/apps/sms/sms-publictoredis
  tag: dev-8557e9b47eaf36e1a162b399d85afc212dd5d1b7
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  general-contentlength: "1600"
  general-send-sms-api: 1
  general-sleep: "5000"
  general-roundsize: "40000"
  general-domain-shorten: "c0c.ants.co.th/"
  general-linkbacklist: " ต้องการยกเลิก SMS จากทางเราคลิก https://block.message-info.me/"
  general-smstrantype: "1"
  general-isOperator: "TRUE"
  # setting general

  # setting rabbitmq start
  rabbit-host: "rabbitmq.rebbitmq.svc.cluster.local"
  rabbit-port: "5672" # 15672
  rabbit-user: "user"
  rabbit-password: "1Hg97BdkKEJjthaQ"
  rabbit-queue-true-isgame: ""
  rabbit-queue-true: "2325131108"
  rabbit-queue-dtac: "1684068"
  # setting rabbitmq end

  # setting connectionstring start
  con-account: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ACCOUNT_KUBE;Data Source=210.1.61.185,14430"
  con-blacklist: "Data Source=210.1.61.185,14430;Initial Catalog=BLACKLIST;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  con-exception: "Server=tcp:antsdb.database.windows.net,1433;Initial Catalog=LOGS_DB;Persist Security Info=False;User ID=ants_sa;Password='P@ssw0rd;';MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=180;"
  # setting connectionstring end

  # list env and connection string start
  listDb: "ants1 axa bmw"
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE;Data Source=210.1.61.185,14430"
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV1;Data Source=210.1.61.185,14430"
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV2;Data Source=210.1.61.185,14430"
  shorten-ants1: "Data Source=210.1.61.185,14430;Initial Catalog=SHORTEN;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  shorten-axa: "Data Source=210.1.61.185,14430;Initial Catalog=SHORTEN_AXA;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  shorten-bmw: "Data Source=210.1.61.185,14430;Initial Catalog=SHORTEN;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"
  # list env and connection string end

  # setting redis start
  redis-key: "PUBAPI_SMSREQ:"
  redis-limit-send: "redis-limitsend-master.database.svc.cluster.local:6379"
  redis-dev: "redis-public-dev-master.database.svc.cluster.local:6379"
  redis-ants1: "redis-public-ants-master.database.svc.cluster.local:6379"
  redis-axa: "redis-public-axa-master.database.svc.cluster.local:6379"
  redis-bmw: "redis-public-bmw-master.database.svc.cluster.local:6379"
  # setting redis end

  # setting task start
  task-size-env: 2
  task-env: 2
  # setting task end
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: publictoredis-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-publictoredis
        type: DirectoryOrCreate
  volumeMounts:
    - name: publictoredis-logs
      mountPath: /app/logs/publictoredis-container

      