kind: Deployment
replicaCount: 1
name: sms-sendsms
image:
  repository: registry.ants.co.th/apps/sms/sms-sendsms
  tag: dev-35abe502b83c8ef7e5b64aa39d74e6d09c86fe71
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  RABBITMQ_URI: "amqp://user:1Hg97BdkKEJjthaQ@rabbitmq.rebbitmq.svc.cluster.local:5672"
  RABBITMQ_NAME: "2325131108"
  TPS_LIMIT: "80"
  MongoConnect: "mongodb://210.1.61.187:37017"
  MongoDb: "logdb"
  MongoCollection: "testRabbit"
  shortenUrlDomain: "c0c.ants.co.th/"
  DB_SMS: "Server='210.1.61.185,14430';Database='SMS_KUBE';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  DB_SHORTEN: "Server='210.1.61.185,14430';Database='SHORTEN';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"
  oper_true_password: ""
  oper_true_service_id: ""
  oper_true_url: ""
  oper_true_short_code: ""
  oper_true_charge_number: ""
  oper_dtac_user: "api1684068"
  oper_dtac_password: "bviwr4xq"
  oper_dtac_url: "https://apismsplus6.dtac.co.th/servlet/api/sms/submit"
  isQuicksend: "0"
  isTest: "1"
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  closeLog: "0"
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}

volumes:
  enabled: true
  volume:
    - name: sendsms-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-sendsms
        type: DirectoryOrCreate
  volumeMounts:
    - name: sendsms-logs
      mountPath: /app/logs/sendsms-container
