kind: Deployment
replicaCount: 1
name: sms-private
image:
  repository: registry.ants.co.th/apps/sms/sms-private
  tag: dev-ef87e01951529bb96e2ca571d0c935b7d96ac0be
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv:
  AllowedHosts: "*"
  accountDbCenter: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ACCOUNT_KUBE;Data Source=210.1.61.185,14430"
  accountDbEntities: "metadata=res://*/ANTNotifyModel.csdl|res://*/ANTNotifyModel.ssdl|res://*/ANTNotifyModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=210.1.61.185,14430;initial catalog=ACCOUNT_KUBE;persist security info=True;user id=sa;password='P@ssw0rd;';multipleactiveresultsets=True;application name=EntityFramework&quot;"
  logCenterDb: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=LOG_CENTER;Data Source=210.1.61.185,14430"

  smsCreditBalanceDb: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=DEV_SMSCREDITBALANCE;Data Source=210.1.61.185,14431"
  backListDb: "Data Source=210.1.61.185,14430;Initial Catalog=BLACKLIST;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  reportCenter: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=REPORT_CENTER;Data Source=210.1.61.185,14430"
  tokenAccountDb: "Server='210.1.61.185,14430';Database='ACCOUNT_KUBE';User Id='sa';Password='P@ssw0rd;';TrustServerCertificate=True;"

  ants1: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  ants2: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  ants4: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  axa: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE_PROD_ENV1;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP_ENV1;Data Source=210.1.61.185,14430"
  otpDb_axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2_ENV1;Data Source=210.1.61.185,14430"

  bmw: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE_PROD_ENV2;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  hospital: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  promotech: "Server=210.1.61.185,14430,14430;Database=SMS_KUBE;User Id=sa;Password='P@ssw0rd;';Encrypt=True;TrustServerCertificate=True;"
  smsReportTempDb_promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_REPORT_TEMP;Data Source=210.1.61.185,14430"
  otpDb_promotec: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTSOTP_DEV2;Data Source=210.1.61.185,14430"

  shortenDb_ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  shortenDb_ants2: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  shortenDb_ants4: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  shortenDb_axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN_AXA;Data Source=210.1.61.185,14430"
  shortenDb_bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  shortenDb_hospital: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  shortenDb_promotech: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SHORTEN;Data Source=210.1.61.185,14430"
  MongoDBConnection_ants1: "mongodb://210.1.61.187:37017/logdb?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_ants2: "mongodb://210.1.61.187:37017/ants2?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_ants4: "mongodb://210.1.61.187:37017/ants4?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_axa: "mongodb://210.1.61.187:37017/axa?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_bmw: "mongodb://210.1.61.187:37017/bmw?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_hospital: "mongodb://210.1.61.187:37017/hospital?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  MongoDBConnection_promotech: "mongodb://210.1.61.187:37017/promotech?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"
  # //Announce
  announcementDb: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=ANTS_ANNOUNCEMENT;Data Source=210.1.61.185,14430"
  # //use in EmailBiz.cs
  apikey_taximail: "62b2b64fcf36b541db82be97a85188fe894cfcee"
  secretkey_taximail: "6259a052fa60cd26487beab84b233b40925e2999"
  Generate_sessionid_url: "https://api.taximail.com/v2/user/login"
  SendemailTaximail_url: "https://api.taximail.com/v2/transactional"
  emailto: "phatarawan.k@ants.co.th"
  auth_email: "security@ants.co.th"
  auth_passowrd: "Ants2015$"
  GetFileEcm_Url: "http://27.254.150.101:51010/api/file/getfile/"
  GetFileNewEcm_Url: "http://119.63.68.220:51010/api/file/getfile/"
  # // upload file
  auth_newecm: "smsapi:P@ssw0rd"
  UploadNewEcm_Url: "http://119.63.68.220:51010/api/file/uploadfile_formdata"
  UploadEcm_Url: "http://119.63.68.220:51010/api/file/getfile/"
  # // OTP
  UrlOTP: "https://otp.ants.co.th"
  urlTransactionInfo: "http://119.63.68.215:9100/createTransactionInfo"
  urlConection: "http://103.212.181.11:3002/getConfig/"
  gateway_otp: "http://103.212.181.33:2020/SMSGateway/true"
  gateway_otp_user: "2317451103"
  gateway_otp_pass: "GnSm8392"
  service_id: "2317451103"
  charge_number: "40001308"

  # // Files
  Filemaxlength: "10485760"
  # // FTP
  urltestftpconnect: "http://103.212.181.11:4101/TestFtpConnect"
  # // QuickSend, using in SMSAPIBiz.cs
  contentlength: "1600"
  send_sms_api: "1"
  urlcreateSmsReqQuickSend: "http://119.63.68.215:4005/createSmsReqQuickSend"
  # // ApiDeleteRedis
  ApiDeleteRedis: "https://sms-apideleteredis-dev.ants.co.th/api/redis/del"
  enpointUrl_Token: "https://sms-gettoken-dev.ants.co.th/api/GetToken/login"
  # // Shorten URL domain
  shortenUrlDomain: "c0c.ants.co.th/"
  # // config อยู่ใน File ~/business/v1/SMSAPIBiz.cs
  RedisConnect: "unuse"
  RedisKey: "unuse"
  RedisConnectsend: "unuse"
  RedisSend: "unuse"
  Notify_Url: "http://168.63.255.118:51014/SandBox/MO"
  LINK_RESET_PASSWORD_EXPIRE: "240"
  DomailFogetPwd: "https://sms-webs-forgetpassword-dev.ants.co.th/#/forgetpwd/code?code="
  ants1_DomailFogetPwd: "https://sms-webs-forgetpassword-dev.ants.co.th/#/forgetpwd/code?code="
  gateway_creditbalance: "http://13.76.244.175:3002/getCreditV2"
  BLK.MESSAGE: " ต้องการยกเลิก SMS จากทางเราคลิก https://block.message-info.me/"
  expireMinute: "120"
  limitTotalMongo: "200000"
  nodeApiURL: "https://103.212.181.11:3002"
  RegisterUserGateway: "9"
  RegisterUserAccountCost: "0.20"
  RegisterUserAccountErrorCount: "3"
  RegisterUserAccountWebBlockSecond: "180"
  RegisterUserAccountAPIErrorCount: "3"
  RegisterUserAccountAPIBlockSecond: "180"
  RegisterUserParentAccount: "1"
  RegisterUserConnection: "2"
  RegisterUserAPIConnection: "12"
  RegisterUserAccountLevel: "1"
  RegisterUserLevel: "1"
  RegisterUserStatus: "1"
  RegisterUserPaytype: "1"
  RecaptchaSecret: "6LfujJwpAAAAAB4IylNp9yUgY03x_MlhEvlr5_of"
  otpApiUrl: "http://api-service.ants.co.th/"
  otpRegisterUser: "DevANTS1"
  otpRegisterPass: "Dev$@NTS1"
  otcIdRegister: "800cb8f4-6dd7-40e4-b718-31fc727a7f02"
  OmiseAfterChargeBaseReturnUrl: "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed"
  omisekey: "skey_test_5z8gcel4zr2uawdixar"
  omiseExpireQr: "5"
  paymentGateWayApi: "https://dev-papigateway.ants.co.th/"
  paymentGateWayApiToken: "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed"
  ecomSaleDefault: "EcommeceSale@ants.co.th"
  Updateused_discountcode_Url: "https://jaspalapi-pre.azurewebsites.net/Discount/checkdiscountcode?code="
  Get_discountcode_Url: "https://jaspalapi-pre.azurewebsites.net/Discount/checkdiscountcode?code="
  otcId: "fe57607c-a5a2-4732-b671-37eba5533dfe"
  otpUser: "user1"
  otpPass: "P@ssw0rd"
  callbackUrlPaymentGateway: "https://sms-private-dev.ants.co.th/"
  #MongoDBConnection: "mongodb://admin:P%40ssw0rd%3B@223.27.247.217:37010/logdb?authSource=admin&connectTimeoutMS=60000&serverSelectionTimeoutMS=60000&collection=transactions_MonthlyCommu"

  sms_tran_type: "1"
  isOperator: "TRUE"
  rabbitHost: "210.1.61.184"
  rabbitUser: "guest"
  rabbitPass: "guest"
  rabbitQueue: "2317451109"
  rabbitQueueTrue: "2317451109"
  rabbitQueueDtac: "service01"
  ENV_KEY: "dev"
  encrypt-key: "db3OIsj+BXE9NZDy0t8W3TcNekrF+2d/1sFnWG4HnV8TZY30iTOdtVWJG8abWvB1GlOgJuQZdcF2Luqm/hccMw=="
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  closeLog: "0"
imagePullSecrets:
  enabled: true
  createSecret:
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}

volumes:
  enabled: true
  volume:
    - name: private-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-private
        type: DirectoryOrCreate
  volumeMounts:
    - name: private-logs
      mountPath: /app/logs/private-container
# =================================TIMEZONE==========================================
env:
  - name: TZ
    value: "Asia/Bangkok"
