kind: Deployment
replicaCount: 1
name: sms-import-schedule
image:
  repository: registry.ants.co.th/apps/sms/sms-import-schedule
  tag: dev-883ad5eae7963716e9b174e2f446d66a898b7521
  pullPolicy: IfNotPresent
  commandEnabled: false
# ===========================================================================
service:
  enabled: true
  internalPort: 80
  externalPort: 80
appEnv: 
  general-sleep: "3000"
  general-batchname: "IMPORT SCHEDULE"
  dbAccount: "Data Source=210.1.61.185,14430;Initial Catalog=ACCOUNT_KUBE;Persist Security Info=True;User ID=sa;Password='P@ssw0rd;'"

  rabbitHost: "210.1.61.184"
  rabbitUser: "guest"
  rabbitPass: "guest"
  rabbitQueueTrueIsGame: "2317451109"
  rabbitQueueTrue: "2317451109"
  rabbitQueueDtac: "service01"

  listDb: "ants1 axa"
  ants1: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE;Data Source=210.1.61.185,14430"
  axa: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV1;Data Source=210.1.61.185,14430"
  bmw: "Password='P@ssw0rd;';Persist Security Info=True;User ID=sa;Initial Catalog=SMS_KUBE_PROD_ENV2;Data Source=210.1.61.185,14430"
  closeLog: "0"
# ===========================================================================
imagePullSecrets:
  enabled: true
  createSecret: 
    registry: registry.ants.co.th
    username: admin
    password: K1f8kmqOB7xO64nv1VR6z9h3F
# ===========================================================================
resources: {}
volumes:
  enabled: true
  volume:
    - name: import-schedule-logs
      hostPath:
        path: /mnt/data/logs/dev-devcenter-import-schedule
        type: DirectoryOrCreate
  volumeMounts:
    - name: import-schedule-logs
      mountPath: /app/logs/import-schedule-container